### Create region
POST localhost:8080/api/v1/region
Content-Type: application/json

{
  "orderNumber": 1,
  "nameUz": "Toshkent 1",
  "nameRu": "Ташкент 1",
  "nameEn": "Tashkent 1",
  "regionKey": "tashkent1"
}


### Update region
PUT localhost:8080/api/v1/region/1
Content-Type: application/json

{
  "orderNumber": 1,
  "nameUz": "Iqtisodiyot11",
  "nameRu": "Экономика11",
  "nameEn": "Economics11",
  "categoryKey": "iqtisodiyot11"
}


### Delete category
DELETE localhost:8080/api/v1/region/2

### Get region list
GET localhost:8080/api/v1/region/admin

### Get region by lang
GET localhost:8080/api/v1/region/lang
Accept-Language: UZ
